global:
  imagePullSecret: {}
    # name: ""
    # dockerconfigjson: ""
  image: {}
    # registry: gcr.io/my-project
    # tag: latest

replicaCount: 1
port: 8080
serviceAccountName: default

  # To use a digest, change those values like that
  # repository: nginx@sha256
  # tag: 2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
image: {}
  # repository: repo/image
  # registry: gcr.io/my-project
  # tag: latest

imagePullSecret: {}
  # name: ""
  # dockerconfigjson: ""

additionalVolumes: []
# - name: my-volume
#   secret:
#     secretName: my-secret
#   volumeMount:
#     mountPath: /etc/mysecret
#     readOnly: true

ha:
  enabled: true

# resources:
#   limits:
#     cpu: 100m
#     ephemeral-storage: 1G
#     memory: 1G
#   requests:
#     cpu: 100m
#     ephemeral-storage: 1G
#     memory: 1G

health_check:
  liveness:
    path: /healthz
  readiness:
    path: /healthz

startupTimeout: 30

envSecretNames: []

env: {}
# env:
#   key: value

expose:
  enabled: true
  # host: ""

# bindings:
#   ui5-repo-servicerepo:
#     serviceInstanceName: ui5-repo-instance
#     externalName: ui5-kyma-binding
#     secretName: ui5-repo-binding-secret
#     parameters:
#       foo: bar
#     parametersFrom:
#       - secretKeyRef:
#           key: test
#           name: test
#     credentialsRotationPolicy:
#       enabled: true
#   hana:
#     serviceInstanceName: hana-manual
#   portal:
#     fromSecret: manual-secret # user-provided-service
