apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "web-application.labels" . | nindent 4 }}
  name: {{ include "web-application.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "web-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "web-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- if (include "web-application.imagePullSecretName" .) }}
      imagePullSecrets:
        - name: {{ include "web-application.imagePullSecretName" . }}
      {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - image: {{ include "web-application.imageName" . }}
        name: {{ include "web-application.name" . }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        envFrom:
        {{- range $secretName := .Values.envSecretNames }}
        - secretRef:
            name: {{ $secretName }}
        {{- end }}
        env:
        {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
        {{- if not .Values.env.APPLICATION_NAME }}
        - name: APPLICATION_NAME
          value: {{ include "web-application.fullname" . }}
        {{- end }}
        {{- if not .Values.env.APPLICATION_URI }}
        - name: APPLICATION_URI
          value: {{ include "web-application.applicationUri" . }}
        {{- end }}
        {{- if .Values.bindings }}
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        {{- end }}
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: TMPDIR
          value: /tmp
        livenessProbe:
        {{- if .Values.health_check.liveness.path }}
          httpGet:
            path: {{ .Values.health_check.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        readinessProbe:
        {{- if .Values.health_check.readiness.path }}
          httpGet:
            path: {{ .Values.health_check.readiness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        startupProbe:
        {{- if .Values.health_check.liveness.path }}
          httpGet:
            path: {{ .Values.health_check.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
          failureThreshold: {{ div (add1 .Values.startupTimeout) 2 }}
          periodSeconds: 2
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- range $volume := .Values.additionalVolumes }}
        - name: {{ $volume.name | quote }}
          {{- toYaml $volume.volumeMount  | nindent 10 }}
        {{- end }}
        {{- include "web-application.serviceMounts" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      {{- if .Values.ha.enabled }}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels: {{- include "web-application.selectorLabels" . | nindent 12 }}
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      {{- end }}
      volumes:
      - emptyDir: {}
        name: tmp
      {{- include "web-application.serviceVolumes" . | nindent 6 }}
      {{- range $volume := .Values.additionalVolumes }}
      -
        {{- omit $volume "volumeMount" | toYaml  | nindent 8 }}
      {{- end }}
