apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "web-application.fullname" . }}
  labels: {{- include "web-application.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: istio-ingressgateway
      namespaceSelector:
        matchLabels:
          name: istio-system
  podSelector:
    matchLabels: {{- include "web-application.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
